version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_USER=sapiens
      - DB_PASS=STHbntr0dI3fU6Ty
      - DB_NAME=user-management
    command: npm start
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  db:
    image: mongo:4.4
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: user-management
      MONGO_INITDB_ROOT_USERNAME: sapiens
      MONGO_INITDB_ROOT_PASSWORD: STHbntr0dI3fU6Ty

volumes:
  db-data:
